# Generated by Django 5.1.13 on 2025-10-28 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0005_alter_usuariodispositivo_grupo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Código interno o número de nómina', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('doc_id', models.CharField(help_text='Documento de identidad', max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=120)),
                ('departamento', models.CharField(blank=True, max_length=80)),
                ('area', models.CharField(blank=True, max_length=80)),
                ('seccion', models.CharField(blank=True, max_length=80)),
                ('tipo_vinculacion', models.CharField(choices=[('FUNC', 'Funcionario'), ('PRAC', 'Practicante'), ('CONT', 'Contratado')], default='FUNC', help_text='Tipo de relación laboral', max_length=5)),
                ('puesto', models.CharField(blank=True, help_text='Cargo o puesto laboral', max_length=100)),
                ('user_id', models.CharField(blank=True, help_text='ID en el sistema biométrico', max_length=32)),
                ('uid', models.PositiveIntegerField(blank=True, help_text='UID interno del equipo', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='dispositivos.dispositivo')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['numero'], name='empleados_e_numero_20d41c_idx'), models.Index(fields=['doc_id'], name='empleados_e_doc_id_f5fbda_idx'), models.Index(fields=['departamento', 'area'], name='empleados_e_departa_37abca_idx'), models.Index(fields=['dispositivo', 'user_id'], name='empleados_e_disposi_99d881_idx')],
            },
        ),
    ]
