# Generated by Django 5.2.8 on 2025-12-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/fotos/'),
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('doc_id', models.CharField(help_text='Documento de identidad', max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('skills', models.TextField(blank=True, help_text='Habilidades técnicas o blandas')),
                ('titulaciones', models.TextField(blank=True, help_text='Títulos y certificaciones')),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('PROC', 'En Proceso'), ('DESC', 'Descartado'), ('CONTR', 'Contratado')], default='DISP', max_length=5)),
                ('nota', models.TextField(blank=True, help_text='Notas internas sobre el candidato')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['doc_id'], name='empleados_c_doc_id_efd63e_idx'), models.Index(fields=['apellido'], name='empleados_c_apellid_8e525b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('ID', 'Documento Identidad'), ('TIT', 'Título / Certificación'), ('CON', 'Contrato'), ('EXP', 'Expediente General'), ('OTRO', 'Otro')], default='OTRO', max_length=5)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción breve del archivo', max_length=150)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empleados.candidato')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empleados.empleado')),
            ],
        ),
    ]
