# Generated by Django 5.2.8 on 2025-12-18 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_foto_candidato_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Salario base mensual', max_digits=12),
        ),
        migrations.CreateModel(
            name='BajaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('VACA', 'Vacaciones'), ('ENFE', 'Enfermedad / Médica'), ('PERM', 'Permiso Personal'), ('OTRO', 'Otro')], default='OTRO', max_length=5)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas_autorizadas', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Baja Autorizada',
                'verbose_name_plural': 'Bajas Autorizadas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
