# Generated by Django 5.2.8 on 2025-12-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_empleado_salario_base_bajaautorizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('nota', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Periodo de Nómina',
                'verbose_name_plural': 'Periodos de Nómina',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='NominaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dias_ausencia', models.IntegerField(default=0)),
                ('monto_descuento_ausencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('neto_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reportes.nominaperiodo')),
            ],
            options={
                'unique_together': {('periodo', 'empleado')},
            },
        ),
    ]
