# Generated by Django 5.1.13 on 2025-10-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('puerto', models.PositiveIntegerField(default=4370)),
                ('protocolo', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=3)),
                ('password', models.CharField(blank=True, help_text='Si el equipo tiene contraseña', max_length=64)),
                ('timeout', models.PositiveIntegerField(default=5, help_text='Segundos de espera de socket')),
                ('omitir_ping', models.BooleanField(default=False, help_text='Intentar conectar sin ping previo')),
                ('max_size_tcp', models.PositiveIntegerField(default=1024)),
                ('max_size_udp', models.PositiveIntegerField(default=1024)),
                ('tz', models.CharField(default='Africa/Malabo', max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_descarga', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('ip', 'puerto'), name='uq_ip_puerto')],
            },
        ),
    ]
