# Generated by Django 5.1.13 on 2025-10-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(help_text='Identificador interno único (uid)')),
                ('user_id', models.CharField(help_text='ID mostrado en el equipo', max_length=32)),
                ('nombre', models.CharField(max_length=64)),
                ('privilegio', models.PositiveSmallIntegerField(default=0, help_text='0=Usuario, 14=Admin')),
                ('grupo_id', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='dispositivos.dispositivo')),
            ],
            options={
                'ordering': ['dispositivo', 'uid'],
                'unique_together': {('dispositivo', 'uid')},
            },
        ),
    ]
