# Generated by Django 5.1.13 on 2025-10-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_usuariodispositivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='omitir_ping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='timeout',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='usuariodispositivo',
            name='privilegio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AsistenciaCruda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('uid', models.PositiveIntegerField(blank=True, null=True)),
                ('ts', models.DateTimeField()),
                ('status', models.SmallIntegerField()),
                ('punch', models.SmallIntegerField(blank=True, null=True)),
                ('raw_status', models.CharField(blank=True, max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcajes', to='dispositivos.dispositivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcajes', to='dispositivos.usuariodispositivo')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['ts'], name='dispositivo_ts_94bfdc_idx'), models.Index(fields=['dispositivo', 'user_id'], name='dispositivo_disposi_ac715e_idx')],
                'constraints': [models.UniqueConstraint(fields=('dispositivo', 'user_id', 'ts', 'status'), name='uq_marcaje_unico')],
            },
        ),
    ]
