# Generated by Django 5.1.13 on 2025-10-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_alter_dispositivo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariodispositivo',
            options={'ordering': ['dispositivo', 'user_id', 'uid']},
        ),
        migrations.AlterUniqueTogether(
            name='usuariodispositivo',
            unique_together={('dispositivo', 'uid')},
        ),
        migrations.AlterField(
            model_name='usuariodispositivo',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='usuariodispositivo',
            name='uid',
            field=models.PositiveIntegerField(blank=True, help_text='Identificador interno (puede ser nulo)', null=True),
        ),
        migrations.AlterField(
            model_name='usuariodispositivo',
            name='user_id',
            field=models.CharField(blank=True, default='', help_text='ID mostrado en el equipo', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='usuariodispositivo',
            unique_together={('dispositivo', 'uid'), ('dispositivo', 'user_id')},
        ),
    ]
