# Generated by Django 5.1.13 on 2025-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_alter_usuariodispositivo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodispositivo',
            name='grupo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariodispositivo',
            name='privilegio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariodispositivo',
            name='uid',
            field=models.PositiveIntegerField(blank=True, help_text='UID interno, puede ser nulo', null=True),
        ),
    ]
