# Generated by Django 5.1.13 on 2025-10-28 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0005_alter_usuariodispositivo_grupo_id_and_more'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodispositivo',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_dispositivo', to='empleados.empleado'),
        ),
    ]
